name: homepage CICD

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup ssh
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: |
              ${{ secrets.EC2_SSH_PRIVATE_KEY }}
              ${{ secrets.DEPLOY_FRONTEND_KEY }}

      - name: deploy ec2
        run: |
         ssh -o StrictHostKeyChecking=no ubuntu@ip << 'EOF'
           cd ~/amme
           git pull origin main
           npm install
           npm run build

           sudo rm -rf /var/www/html/homepage/*
           sudo cp -r dist/* var/www/homepage/

           echo "frontend deployed"
         EOF
              
